### ISSUE TITLE
MVPリリースに向けてREADME改稿

### ISSUE THREAD

**Issue by Gitnana00** [Gitnana00/Fail_Share#34]
MVPリリース・講師レビューに向けて、より最低限の機能でリリースできるよう改稿を行いたいです。

**Comment by Gitnana00** [comment]
より最小限の機能でMVPリリースを行うため、下記のように修正を行いました。

READMEレビュー時にMVPリリース時点で実装予定だった機能を一部、MVP後に実装としたいです。

### MVP (Minimum Viable Product)
- X,GitHub,Googleアカウントによるユーザー登録,ログイン機能
- パスワード再設定機能
- ゲストユーザー機能

- マークダウン記法に対応
- 失敗を投稿したら、励ましメッセージとともに可愛い画像を表示
- 画像投稿・編集機能
- テンプレート・タグ付け機能

- いいね機能
- ランキング機能

<変更前>
https://github.com/Gitnana00/Fail_Share/pull/1

<変更後>
https://github.com/Gitnana00/Fail_Share/blob/main/README.md

ご確認のほど、よろしくお願いいたします。

**Comment by Tsuchiya2** [comment]
確認しました。
上記LGTMです。
