### ISSUE TITLE
コメント削除機能

### ISSUE THREAD

**Issue by Gitnana00** [Gitnana00/Fail_Share#49]
コメントの編集・削除機能で詰まっているためご相談です。
Ajax化して、画面遷移せずに編集、削除を行いたいのですが、編集ボタンを押すと
`ActionController::UnknownFormat`のエラーが出てしまいます。
(イメージではこのようにしたいです→https://school.runteq.jp/v2/curriculums/rails_basic/chapters/20)

仮説として、ブラウザのコンソールに`Uncaught TypeError: Cannot set properties of undefined (setting 'Rails')`と
`GET http://localhost:3000/comments/11/edit 406 (Not Acceptable)`が出ていることから、
Javascriptの読み込み&表示ができてないのではないかと思っております。

関係がありそうだと思っている箇所
・routes.rb
・importmap.rb
・applicstion.js
・_comment.html.erb

上記のコードを確認しましたが、自分では正しく記載できている認識で、なぜ正しく表示されないのかわからない状況です。

つきましては、エラー解消のために一緒にご確認いただきたいのですがいかがでしょうか？
お忙しい中恐れ入りますが、何卒よろしくお願いいたします。

![Image](https://github.com/Gitnana00/Fail_Share/assets/138284696/b3ffe42f-7869-4118-a275-d737997b8b07)

**Comment by kenchasonakai** [comment]
edit.js.erbとかはありますか？
また、Rails7系使っていたらjs.erbではなくturbo_streamを使いましょう

https://pikawaka.com/rails/respond_to
https://qiita.com/mochimochifarao/items/9c5cd27f554d462f4d2e

**Comment by Gitnana00** [comment]
turbo_streamを使って無事に実装できました！
カリキュラムではできずに飛ばしていた箇所でもあったので、嬉しいです！！
中井さん、ありがとうございました！！
